DROP TABLE CODIGOPOSTAL CASCADE CONSTRAINTS;
DROP TABLE MODO_PAGAMENTO CASCADE CONSTRAINTS;
DROP TABLE TIPOSALA CASCADE CONSTRAINTS;
DROP TABLE SALAS CASCADE CONSTRAINTS;
DROP TABLE TIPOCURSO CASCADE CONSTRAINTS;
DROP TABLE CURSO CASCADE CONSTRAINTS;
DROP TABLE DISCIPLINA CASCADE CONSTRAINTS;
DROP TABLE PROFESSOR CASCADE CONSTRAINTS;
DROP TABLE PROFESSOR_DISCIPLINA CASCADE CONSTRAINTS;
DROP TABLE ALUNO CASCADE CONSTRAINTS;
DROP TABLE SESSAO CASCADE CONSTRAINTS;
DROP TABLE ALUNO_SESSAO CASCADE CONSTRAINTS;
DROP TABLE PAGAMENTO CASCADE CONSTRAINTS;
DROP TABLE MENSALIDADE CASCADE CONSTRAINTS;
DROP TABLE ALUNO_MENSALIDADE CASCADE CONSTRAINTS;

CREATE TABLE CODIGOPOSTAL (
    CPOSTAL VARCHAR(8) NOT NULL,
    LOCALIDADE VARCHAR(25) NOT NULL,
    PRIMARY KEY (CPOSTAL)
);

CREATE TABLE MODO_PAGAMENTO (
    ID_MODOPAG CHAR(4) NOT NULL,
    DESCRICAO VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_MODOPAG)
);

CREATE TABLE TIPOSALA (
    ID_TIPO INTEGER NOT NULL,
    DESCRICAO VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_TIPO)
);

CREATE TABLE SALAS (
    ID_SALA CHAR(4) NOT NULL,
    ID_TIPO INTEGER NOT NULL,
    PRIMARY KEY (ID_SALA)
);

CREATE TABLE TIPOCURSO (
    ID_TIPO INTEGER NOT NULL,
    DESCRICAO VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_TIPO)
);

CREATE TABLE CURSO (
    ID_CURSO INTEGER NOT NULL,
    SIGLA VARCHAR(6) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    ID_TIPO INTEGER NOT NULL,
    PRIMARY KEY (ID_CURSO)
);

CREATE TABLE DISCIPLINA (
    ID_DISCIPLINA INTEGER NOT NULL,
    SIGLA VARCHAR(4) NOT NULL,
    DESCRICAO VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_DISCIPLINA)
);

CREATE TABLE PROFESSOR (
    ID_PROFESSOR CHAR(4) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    RUA VARCHAR(50) NOT NULL,
    NPORTA INTEGER NOT NULL,
    CPOSTAL VARCHAR(8) NOT NULL,
    TELEFONE INTEGER NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    NIF INTEGER NOT NULL,
    PRIMARY KEY (ID_PROFESSOR)
);

CREATE TABLE PROFESSOR_DISCIPLINA (
    ID_DISCIPLINA INTEGER NOT NULL,
    ID_PROFESSOR CHAR(4) NOT NULL,
    PRIMARY KEY (ID_DISCIPLINA, ID_PROFESSOR)
);

CREATE TABLE ALUNO (
    NUM_ALUNO INTEGER NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    ID_CURSO INTEGER NOT NULL,
    RUA VARCHAR(50) NOT NULL,
    NPORTA INTEGER NOT NULL,
    CPOSTAL VARCHAR(8) NOT NULL,
    TELEFONE INTEGER NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    NIF INTEGER NOT NULL,
    PRIMARY KEY (NUM_ALUNO)
);

CREATE TABLE SESSAO (
    NUM_SESSAO INTEGER NOT NULL,
    DATA DATE NOT NULL,
    HORA_FIM VARCHAR(5) NOT NULL,
    HORA_INICIO VARCHAR(5) NOT NULL,
    ID_DISCIPLINA INTEGER NOT NULL,
    ID_PROFESSOR CHAR(4) NOT NULL,
    ID_SALA CHAR(4) NOT NULL,
    NMENSALIDADE INTEGER NOT NULL,
    PRIMARY KEY (NUM_SESSAO)
);

CREATE TABLE ALUNO_SESSAO (
    NUM_ALUNO INTEGER NOT NULL,
    NUM_SESSAO INTEGER NOT NULL,
    PRIMARY KEY (NUM_ALUNO, NUM_SESSAO)
);

CREATE TABLE PAGAMENTO (
    NUM_PAGAMENTO INTEGER NOT NULL,
    NMENSALIDADE INTEGER NOT NULL,
    VALOR_TOTAL NUMERIC(5,2) NOT NULL,
    DATA_PAGAMENTO DATE NOT NULL,
    NUM_ALUNO INTEGER NOT NULL,
    ID_MODOPAG CHAR(4) NOT NULL,
    PRIMARY KEY (NUM_PAGAMENTO)
);

CREATE TABLE MENSALIDADE (
    NMENSALIDADE INTEGER NOT NULL,
    MES VARCHAR(20) NOT NULL,
    ANO VARCHAR(4) NOT NULL,
    PRIMARY KEY (NMENSALIDADE)
);

CREATE TABLE ALUNO_MENSALIDADE (
    NMENSALIDADE INTEGER NOT NULL,
    NUM_ALUNO INTEGER NOT NULL,
    VALOR NUMERIC(5,2) NOT NULL,
    PRIMARY KEY (NMENSALIDADE, NUM_ALUNO)
);

ALTER TABLE SALAS ADD FOREIGN KEY (ID_TIPO) REFERENCES TIPOSALA(ID_TIPO);
ALTER TABLE CURSO ADD FOREIGN KEY (ID_TIPO) REFERENCES TIPOCURSO(ID_TIPO);
ALTER TABLE PROFESSOR ADD FOREIGN KEY (CPOSTAL) REFERENCES CODIGOPOSTAL(CPOSTAL);
ALTER TABLE PROFESSOR_DISCIPLINA ADD FOREIGN KEY (ID_DISCIPLINA) REFERENCES DISCIPLINA(ID_DISCIPLINA);
ALTER TABLE PROFESSOR_DISCIPLINA ADD FOREIGN KEY (ID_PROFESSOR) REFERENCES PROFESSOR(ID_PROFESSOR);
ALTER TABLE ALUNO ADD FOREIGN KEY (CPOSTAL) REFERENCES CODIGOPOSTAL(CPOSTAL);
ALTER TABLE ALUNO ADD FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO);
ALTER TABLE SESSAO ADD FOREIGN KEY (ID_SALA) REFERENCES SALAS(ID_SALA);
ALTER TABLE SESSAO ADD FOREIGN KEY (ID_DISCIPLINA) REFERENCES DISCIPLINA(ID_DISCIPLINA);
ALTER TABLE SESSAO ADD FOREIGN KEY (ID_PROFESSOR) REFERENCES PROFESSOR(ID_PROFESSOR);
ALTER TABLE SESSAO ADD FOREIGN KEY (NMENSALIDADE) REFERENCES MENSALIDADE(NMENSALIDADE);
ALTER TABLE ALUNO_SESSAO ADD FOREIGN KEY (NUM_ALUNO) REFERENCES ALUNO(NUM_ALUNO);
ALTER TABLE ALUNO_SESSAO ADD FOREIGN KEY (NUM_SESSAO) REFERENCES SESSAO(NUM_SESSAO);
ALTER TABLE PAGAMENTO ADD FOREIGN KEY (ID_MODOPAG) REFERENCES MODO_PAGAMENTO(ID_MODOPAG);
ALTER TABLE PAGAMENTO ADD FOREIGN KEY (NUM_ALUNO) REFERENCES ALUNO(NUM_ALUNO);
ALTER TABLE PAGAMENTO ADD FOREIGN KEY (NMENSALIDADE) REFERENCES MENSALIDADE(NMENSALIDADE);
ALTER TABLE ALUNO_MENSALIDADE ADD FOREIGN KEY (NUM_ALUNO) REFERENCES ALUNO(NUM_ALUNO);
ALTER TABLE ALUNO_MENSALIDADE ADD FOREIGN KEY (NMENSALIDADE) REFERENCES MENSALIDADE(NMENSALIDADE);


-- INSERIR DADOS EM ALGUMAS TABELAS PARA TESTAR

-- INSERT CODIGOS POSTAIS
INSERT INTO CODIGOPOSTAL(CPOSTAL, LOCALIDADE) VALUES('4970-555','SÃO COSME E SÃO DAMIÃO');
INSERT INTO CODIGOPOSTAL(CPOSTAL, LOCALIDADE) VALUES('4970-441','PRAÇA MUNICIPAL');
INSERT INTO CODIGOPOSTAL(CPOSTAL, LOCALIDADE) VALUES('4900-357','RUA SANTIAGO DA BARRA');

-- INSERT TIPOS DE CURSO
INSERT INTO TIPOCURSO(ID_TIPO, DESCRICAO) VALUES(1,'CURSO PROFISSIONAL');
INSERT INTO TIPOCURSO(ID_TIPO, DESCRICAO) VALUES(2,'LICENCIATURA');
INSERT INTO TIPOCURSO(ID_TIPO, DESCRICAO) VALUES(3,'MESTRADO');
INSERT INTO TIPOCURSO(ID_TIPO, DESCRICAO) VALUES(4,'DOUTORAMENTO');

-- INSERT CURSOS
INSERT INTO CURSO(ID_CURSO, SIGLA, NOME, ID_TIPO) VALUES(9119,'EI','ENGENHARIA INFORMATICA',2);
INSERT INTO CURSO(ID_CURSO, SIGLA, NOME, ID_TIPO) VALUES(9147,'G','GESTÃO',2);
INSERT INTO CURSO(ID_CURSO, SIGLA, NOME, ID_TIPO) VALUES(6797,'MTGSI','MESTRADO TEC. E GESTÃO SISTEMAS DE INFORMAÇÃO',3);
INSERT INTO CURSO(ID_CURSO, SIGLA, NOME, ID_TIPO) VALUES(067,'CTSPIG','CTSP DE INFORMATICA DE GESTÃO',1);
INSERT INTO CURSO(ID_CURSO, SIGLA, NOME, ID_TIPO) VALUES(5141,'DEI','DOUTORAMENTO ENGENHARIA INFORMATICA',4);

-- INSERT TIPOSALA
INSERT INTO TIPOSALA(ID_TIPO, DESCRICAO) VALUES(1,'SALA');
INSERT INTO TIPOSALA(ID_TIPO, DESCRICAO) VALUES(2,'LABORATORIO');
INSERT INTO TIPOSALA(ID_TIPO, DESCRICAO) VALUES(3,'AUDITORIO');

-- INSERT SALAS
INSERT INTO SALAS(ID_SALA, ID_TIPO) VALUES('S1.1',1);
INSERT INTO SALAS(ID_SALA, ID_TIPO) VALUES('S1.2',1);
INSERT INTO SALAS(ID_SALA, ID_TIPO) VALUES('S2.1',1);
INSERT INTO SALAS(ID_SALA, ID_TIPO) VALUES('S2.2',1);
INSERT INTO SALAS(ID_SALA, ID_TIPO) VALUES('S2.3',1);
INSERT INTO SALAS(ID_SALA, ID_TIPO) VALUES('L1.1',2);
INSERT INTO SALAS(ID_SALA, ID_TIPO) VALUES('L1.2',2);
INSERT INTO SALAS(ID_SALA, ID_TIPO) VALUES('L1.3',2);
INSERT INTO SALAS(ID_SALA, ID_TIPO) VALUES('A1.1',3);
INSERT INTO SALAS(ID_SALA, ID_TIPO) VALUES('A2.1',3);

-- INSERT DISCIPLINAS
INSERT INTO DISCIPLINA(ID_DISCIPLINA, SIGLA, DESCRICAO) VALUES(1,'BD','BASE DE DADOS');
INSERT INTO DISCIPLINA(ID_DISCIPLINA, SIGLA, DESCRICAO) VALUES(2,'ASC','ARQUITETURA E SISTEMAS DE COMPUTADORES');
INSERT INTO DISCIPLINA(ID_DISCIPLINA, SIGLA, DESCRICAO) VALUES(3,'IHM','INTERAÇÃO HOMEM-MAQUINA');
INSERT INTO DISCIPLINA(ID_DISCIPLINA, SIGLA, DESCRICAO) VALUES(4,'IA','INTELIGENCIA ARTIFICIAL');
INSERT INTO DISCIPLINA(ID_DISCIPLINA, SIGLA, DESCRICAO) VALUES(5,'ABD','ADMINISTRAÇÃO DE BASE DE DADOS');

-- INSERT PROFESSORES
INSERT INTO PROFESSOR(ID_PROFESSOR, NOME, RUA, NPORTA, CPOSTAL, TELEFONE, EMAIL, NIF)
VALUES('P001','VASCO SILVA','RUA SANTIAGO DA BARRA',17,'4900-357',965789987,'vascosilva@ipvc.pt',123456789);
INSERT INTO PROFESSOR(ID_PROFESSOR, NOME, RUA, NPORTA, CPOSTAL, TELEFONE, EMAIL, NIF)
VALUES('P002','ANA MIRANDA','CASTANHEIRA',54,'4970-555',912343211,'mirandaana@ipvc.pt',987654321);
INSERT INTO PROFESSOR(ID_PROFESSOR, NOME, RUA, NPORTA, CPOSTAL, TELEFONE, EMAIL, NIF)
VALUES('P003','ANTONIO ALVES','RUA DA LIBERDADE',7,'4970-441',933444555,'a.alves@ipvc.pt',543219876);

-- INSERT PROFESSOR_DISCIPLINA
INSERT INTO PROFESSOR_DISCIPLINA(ID_DISCIPLINA, ID_PROFESSOR) VALUES(1,'P003');
INSERT INTO PROFESSOR_DISCIPLINA(ID_DISCIPLINA, ID_PROFESSOR) VALUES(2,'P001');
INSERT INTO PROFESSOR_DISCIPLINA(ID_DISCIPLINA, ID_PROFESSOR) VALUES(3,'P002');
INSERT INTO PROFESSOR_DISCIPLINA(ID_DISCIPLINA, ID_PROFESSOR) VALUES(4,'P002');
INSERT INTO PROFESSOR_DISCIPLINA(ID_DISCIPLINA, ID_PROFESSOR) VALUES(5,'P001');

-- INSERT ALUNO
INSERT INTO ALUNO(NUM_ALUNO, NOME, DATA_NASCIMENTO, ID_CURSO, RUA, NPORTA, CPOSTAL, TELEFONE, EMAIL, NIF)
VALUES(17512,'PEDRO SILVA',TO_DATE('18/03/1996', 'DD/MM/YYYY'), 9119, 'GEREI',105,'4970-555',933333333,'phvsilva@ipvc.pt',123456789);
INSERT INTO ALUNO(NUM_ALUNO, NOME, DATA_NASCIMENTO, ID_CURSO, RUA, NPORTA, CPOSTAL, TELEFONE, EMAIL, NIF)
VALUES(17485,'DIOGO CORREIA',TO_DATE('21/07/1998', 'DD/MM/YYYY'), 5141, 'ZINDE',10,'4970-441',933543768,'diogo@ipvc.pt',635643587);
INSERT INTO ALUNO(NUM_ALUNO, NOME, DATA_NASCIMENTO, ID_CURSO, RUA, NPORTA, CPOSTAL, TELEFONE, EMAIL, NIF)
VALUES(6875,'RITA BRANCO',TO_DATE('18/05/1987', 'DD/MM/YYYY'), 9147, 'AVENIDA FIXE',132,'4970-555',961345765,'rita@ipvc.pt',654321987);
INSERT INTO ALUNO(NUM_ALUNO, NOME, DATA_NASCIMENTO, ID_CURSO, RUA, NPORTA, CPOSTAL, TELEFONE, EMAIL, NIF)
VALUES(342,'PAULO LOPES',TO_DATE('02/01/1986', 'DD/MM/YYYY'), 67, 'RUA DA CIDADE',46,'4900-357',933456743,'paulo@ipvc.pt',456789321);

--CRIAR SEQUENCIA NUM_SESSAO
CREATE SEQUENCE NUM_SESSAO
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
 -- CRIAÇAO SEQUENCIA NMENSALIDADE
CREATE SEQUENCE NMENSALIDADE
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
 
--INSERT MENSALIDADE
INSERT INTO MENSALIDADE VALUES(NMENSALIDADE.NEXTVAL, TO_CHAR(EXTRACT(MONTH FROM SYSDATE)), TO_CHAR(EXTRACT(YEAR FROM SYSDATE)));
INSERT INTO MENSALIDADE VALUES(NMENSALIDADE.NEXTVAL,'01','2019');
INSERT INTO MENSALIDADE VALUES(NMENSALIDADE.NEXTVAL, '02','2019');
INSERT INTO MENSALIDADE VALUES(NMENSALIDADE.NEXTVAL, '03','2019');
INSERT INTO MENSALIDADE VALUES(NMENSALIDADE.NEXTVAL, '04','2019');
INSERT INTO MENSALIDADE VALUES(NMENSALIDADE.NEXTVAL, '05','2019');
-- INSERT SESSAO
INSERT INTO SESSAO(NUM_SESSAO, DATA, HORA_INICIO, HORA_FIM, ID_DISCIPLINA, ID_PROFESSOR, ID_SALA, NMENSALIDADE)
VALUES(NUM_SESSAO.NEXTVAL,TO_DATE('13/12/2018','DD/MM/YYYY'),'10H00','12H00',2,'P001','L1.1',1);
INSERT INTO SESSAO(NUM_SESSAO, DATA, HORA_INICIO, HORA_FIM, ID_DISCIPLINA, ID_PROFESSOR, ID_SALA, NMENSALIDADE)
VALUES(NUM_SESSAO.NEXTVAL,SYSDATE,'14H00','16H00',3,'P002','S2.1',1);
INSERT INTO SESSAO(NUM_SESSAO, DATA, HORA_INICIO, HORA_FIM, ID_DISCIPLINA, ID_PROFESSOR, ID_SALA, NMENSALIDADE)
VALUES(NUM_SESSAO.NEXTVAL,TO_DATE('02/12/2018','DD/MM/YYYY'),'10H00','12H00',5,'P003','L1.2',1);
INSERT INTO SESSAO(NUM_SESSAO, DATA, HORA_INICIO, HORA_FIM, ID_DISCIPLINA, ID_PROFESSOR, ID_SALA, NMENSALIDADE)
VALUES(NUM_SESSAO.NEXTVAL,TO_DATE('01/11/2019','DD/MM/YYYY'),'11H00','13H00',5,'P003','A1.1',2);

--INSERT ALUNO_MENSALIDADE
INSERT INTO ALUNO_MENSALIDADE(NUM_ALUNO, NMENSALIDADE, VALOR) VALUES(17512, 1, 10);
INSERT INTO ALUNO_MENSALIDADE(NUM_ALUNO, NMENSALIDADE, VALOR) VALUES(17485, 1, 10);
INSERT INTO ALUNO_MENSALIDADE(NUM_ALUNO, NMENSALIDADE, VALOR) VALUES(6875, 1, 10);
INSERT INTO ALUNO_MENSALIDADE(NUM_ALUNO, NMENSALIDADE, VALOR) VALUES(342, 1, 10);
INSERT INTO ALUNO_MENSALIDADE(NUM_ALUNO, NMENSALIDADE, VALOR) VALUES(17512, 2, 10);
INSERT INTO ALUNO_MENSALIDADE(NUM_ALUNO, NMENSALIDADE, VALOR) VALUES(17485, 2, 10);
INSERT INTO ALUNO_MENSALIDADE(NUM_ALUNO, NMENSALIDADE, VALOR) VALUES(6875, 2, 10);
INSERT INTO ALUNO_MENSALIDADE(NUM_ALUNO, NMENSALIDADE, VALOR) VALUES(342, 2, 10);

-- INSERT ALUNO_SESSAO
INSERT INTO ALUNO_SESSAO(NUM_ALUNO, NUM_SESSAO) VALUES(17512, 1);
INSERT INTO ALUNO_SESSAO(NUM_ALUNO, NUM_SESSAO) VALUES(17512, 2);
INSERT INTO ALUNO_SESSAO(NUM_ALUNO, NUM_SESSAO) VALUES(17485, 1);
INSERT INTO ALUNO_SESSAO(NUM_ALUNO, NUM_SESSAO) VALUES(17485, 2);
INSERT INTO ALUNO_SESSAO(NUM_ALUNO, NUM_SESSAO) VALUES(6875, 1);
INSERT INTO ALUNO_SESSAO(NUM_ALUNO, NUM_SESSAO) VALUES(342, 1);
INSERT INTO ALUNO_SESSAO(NUM_ALUNO, NUM_SESSAO) VALUES(342, 2);
INSERT INTO ALUNO_SESSAO(NUM_ALUNO, NUM_SESSAO) VALUES(342, 4);
INSERT INTO ALUNO_SESSAO(NUM_ALUNO, NUM_SESSAO) VALUES(17485, 3);
INSERT INTO ALUNO_SESSAO(NUM_ALUNO, NUM_SESSAO) VALUES(17485, 4);
INSERT INTO ALUNO_SESSAO(NUM_ALUNO, NUM_SESSAO) VALUES(6875, 4);

--INSERT MODO_PAGAMENTO
INSERT INTO MODO_PAGAMENTO(ID_MODOPAG, DESCRICAO) VALUES('MB','MULTIBANCO');
INSERT INTO MODO_PAGAMENTO(ID_MODOPAG, DESCRICAO) VALUES('D','DINHEIRO');
INSERT INTO MODO_PAGAMENTO(ID_MODOPAG, DESCRICAO) VALUES('C','CHEQUE');

--CRIAR SEQUENCIA NUM_PAGAMENTO
CREATE SEQUENCE NUM_PAGAMENTO
 START WITH     00001
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

--INSERT PAGAMENTO
INSERT INTO PAGAMENTO(NUM_PAGAMENTO,NMENSALIDADE, VALOR_TOTAL, DATA_PAGAMENTO, NUM_ALUNO, ID_MODOPAG) 
VALUES(NUM_PAGAMENTO.NEXTVAL,1, 0, SYSDATE, 17512, 'MB');
INSERT INTO PAGAMENTO(NUM_PAGAMENTO,NMENSALIDADE, VALOR_TOTAL, DATA_PAGAMENTO, NUM_ALUNO, ID_MODOPAG) 
VALUES(NUM_PAGAMENTO.NEXTVAL,1, 30, SYSDATE, 17485, 'MB');
INSERT INTO PAGAMENTO(NUM_PAGAMENTO,NMENSALIDADE, VALOR_TOTAL, DATA_PAGAMENTO, NUM_ALUNO, ID_MODOPAG) 
VALUES(NUM_PAGAMENTO.NEXTVAL,1, 24, SYSDATE, 342, 'MB');
INSERT INTO PAGAMENTO(NUM_PAGAMENTO,NMENSALIDADE, VALOR_TOTAL, DATA_PAGAMENTO, NUM_ALUNO, ID_MODOPAG) 
VALUES(NUM_PAGAMENTO.NEXTVAL,1, 14, SYSDATE, 6875, 'D');
INSERT INTO PAGAMENTO(NUM_PAGAMENTO,NMENSALIDADE, VALOR_TOTAL, DATA_PAGAMENTO, NUM_ALUNO, ID_MODOPAG) 
VALUES(NUM_PAGAMENTO.NEXTVAL,2, 100, SYSDATE, 6875, 'D');
INSERT INTO PAGAMENTO(NUM_PAGAMENTO,NMENSALIDADE, VALOR_TOTAL, DATA_PAGAMENTO, NUM_ALUNO, ID_MODOPAG) 
VALUES(NUM_PAGAMENTO.NEXTVAL,2, 14, SYSDATE, 17512, 'D');

-- CRIAÇAO DE VIEWS

-- CRIACAO DA VIEW V_PAGAMENTOS
CREATE VIEW V_PAGAMENTOS (NRO_PAGAMENTO,MENSALIDADE, MONTANTE, DATA, NRO_ALUNO, NOME_ALUNO, MODO_PAGAMENTO)
AS
SELECT P.NUM_PAGAMENTO,P.NMENSALIDADE, P.VALOR_TOTAL, P.DATA_PAGAMENTO, P.NUM_ALUNO, A.NOME, MP.DESCRICAO
FROM PAGAMENTO P, MODO_PAGAMENTO MP, ALUNO A
WHERE MP.ID_MODOPAG = P.ID_MODOPAG AND P.NUM_ALUNO = A.NUM_ALUNO
ORDER BY P.NUM_PAGAMENTO DESC;

-- CRIACAO DA VIEW V_ALUNOS
CREATE VIEW V_ALUNOS (NRO_ALUNO, NOME, CURSO, DATA_NASCIMENTO, RUA, PORTA, CODIGO_POSTAL, LOCALIDADE, TELEFONE, EMAIL, NIF)
AS
SELECT A.NUM_ALUNO, A.NOME, C.NOME, A.DATA_NASCIMENTO, A.RUA, A.NPORTA, A.CPOSTAL, CP.LOCALIDADE, A.TELEFONE, A.EMAIL, A.NIF
FROM ALUNO A, CURSO C, CODIGOPOSTAL CP
WHERE A.ID_CURSO = C.ID_CURSO AND A.CPOSTAL = CP.CPOSTAL
ORDER BY NUM_ALUNO ASC;

-- CRIACAO DA VIEW V_PROFESSORES
CREATE VIEW V_PROFESSORES (NRO_PROFESSOR, NOME, RUA, PORTA, CODIGO_POSTAL, LOCALIDADE, TELEFONE, EMAIL, NIF)
AS
SELECT P.ID_PROFESSOR, P.NOME, P.RUA, P.NPORTA, P.CPOSTAL, CP.LOCALIDADE, P.TELEFONE, P.EMAIL, P.NIF
FROM PROFESSOR P, CODIGOPOSTAL CP
WHERE P.CPOSTAL = CP.CPOSTAL
ORDER BY ID_PROFESSOR ASC;

-- CRIAÇAO DA VIEW V_DISCIPLINAS
CREATE VIEW V_DISCIPLINAS (ID_DISCIPLINA, SIGLA, NOME) 
AS
SELECT ID_DISCIPLINA, SIGLA, DESCRICAO FROM DISCIPLINA
ORDER BY ID_DISCIPLINA;

-- CRIAÇAO DA VIEW V_SESSOES
CREATE VIEW V_SESSOES (NRO_SESSAO, DATA, HORA_INICIO, HORA_FIM, DISCIPLINA, PROFESSOR, SALA)
AS
SELECT S.NUM_SESSAO, S.DATA, S.HORA_INICIO, S.HORA_FIM, D.SIGLA, P.NOME, S.ID_SALA
FROM SESSAO S, DISCIPLINA D, PROFESSOR P
WHERE S.ID_DISCIPLINA = D.ID_DISCIPLINA AND S.ID_PROFESSOR = P.ID_PROFESSOR
ORDER BY S.NUM_SESSAO DESC;

-- TRIGGERS
-- TRIGGER PARA ATUALIZAÇAO DO VALOR DA MENSALIDADE DEPOIS DE INSERIR AS SESSOES A QUE O ALUNO ASSISTIU
CREATE OR REPLACE TRIGGER ADDSESSAOMENSALIDADE
    AFTER UPDATE OR INSERT OR DELETE ON ALUNO_SESSAO
      FOR EACH ROW
      DECLARE NROMENSALIDADE INTEGER;
     
  BEGIN
  
  SELECT SESSAO.NMENSALIDADE INTO NROMENSALIDADE
  FROM SESSAO
  WHERE :NEW.NUM_SESSAO = SESSAO.NUM_SESSAO;
  
    UPDATE ALUNO_MENSALIDADE SET ALUNO_MENSALIDADE.VALOR = ALUNO_MENSALIDADE.VALOR + 2 WHERE ALUNO_MENSALIDADE.NUM_ALUNO = :NEW.NUM_ALUNO 
    AND ALUNO_MENSALIDADE.NMENSALIDADE = NROMENSALIDADE;
  END;
  
-- TRIGGER PARA ATUALIZAÇAO DO VALOR DA MENSALIDADE DEPOIS DE INSERIR AS SESSOES A QUE O ALUNO ASSISTIU
CREATE OR REPLACE TRIGGER ADDVALORPAGAMENTO
   BEFORE INSERT ON PAGAMENTO
      FOR EACH ROW
     DECLARE VALOR FLOAT;
     
  BEGIN
  SELECT ALUNO_MENSALIDADE.VALOR INTO VALOR
  FROM ALUNO_MENSALIDADE
  WHERE ALUNO_MENSALIDADE.NMENSALIDADE = :NEW.NMENSALIDADE AND ALUNO_MENSALIDADE.NUM_ALUNO = :NEW.NUM_ALUNO;
  
    :NEW.VALOR_TOTAL := VALOR;
  END;
  
  
-- CONSULTAS SIMPLES
SELECT SUM(VALOR_TOTAL) AS RENDIMENTO FROM PAGAMENTO;
SELECT * FROM ALUNO;  
SELECT * FROM PROFESSOR;
SELECT * FROM SESSAO;
SELECT COUNT(*) AS TOTAL_SESSOES FROM SESSAO;
SELECT COUNT(*) AS TOTAL_ALUNOS FROM ALUNO;
SELECT COUNT(*) AS TOTAL_SALAS FROM SALAS;
SELECT COUNT(*) AS TOTAL_CURSOS FROM CURSO;
SELECT ID_PROFESSOR, NOME, TELEFONE FROM PROFESSOR;
SELECT * FROM SESSAO WHERE DATA >= TO_DATE('01.01.2018','DD.MM.YYYY') AND DATA < TO_DATE('01.01.2019','DD.MM.YYYY');

--CONSULTAS COM JOIN DE TABELAS
SELECT A.NUM_ALUNO, A.NOME, A.TELEFONE
FROM ALUNO A, ALUNO_SESSAO A_S
WHERE A.NUM_ALUNO = A_S.NUM_ALUNO AND A_S.NUM_SESSAO=4;

SELECT P.NUM_PAGAMENTO, P.NUM_ALUNO, A.NOME, P.DATA_PAGAMENTO, P.VALOR_TOTAL
FROM PAGAMENTO P, ALUNO A
WHERE P.NUM_ALUNO = A.NUM_ALUNO AND A.NOME LIKE 'PEDRO SILVA';

SELECT S.NUM_SESSAO, D.SIGLA, D.DESCRICAO
FROM SESSAO S, DISCIPLINA D
WHERE S.ID_DISCIPLINA = D.ID_DISCIPLINA;

-- CONSULTAS COM VIEWS
CREATE VIEW V_PROFESSOR_SESSAO(NUM_SESSAO, DATA, DISCIPLINA, PROFESSOR)
AS
SELECT S.NUM_SESSAO, S.DATA, D.DESCRICAO, P.NOME
FROM SESSAO S, DISCIPLINA D, PROFESSOR P
WHERE S.ID_DISCIPLINA = D.ID_DISCIPLINA
AND S.ID_PROFESSOR = P.ID_PROFESSOR
ORDER BY S.NUM_SESSAO DESC;
    
SELECT DISTINCT PROFESSOR FROM V_PROFESSOR_SESSAO
WHERE DATA >= TO_DATE('01.12.2018','dd.mm.yyyy')
AND DATA < TO_DATE('01.01.2019','dd.mm.yyyy');
    
SELECT DISTINCT A.NOME, V_D.NOME 
FROM ALUNO A, V_DISCIPLINAS V_D, SESSAO S, ALUNO_SESSAO A_S
WHERE A.NUM_ALUNO = A_S.NUM_ALUNO AND A_S.NUM_SESSAO = S.NUM_SESSAO
AND S.ID_DISCIPLINA = V_D.ID_DISCIPLINA
ORDER BY A.NOME;
  
  


INSERT INTO ALUNO_SESSAO VALUES(342, 2);
INSERT INTO ALUNO_SESSAO VALUES(6875, 2);


 
